---
- hosts: all
  remote_user: ansible
  become: true
  tasks:

    - name: Node is alive
      command: "ping -c3 172.19.44.124"
      when: ping_status.rc != 1
      register: ping
      set_fact:
          status: "alive"

    - name: Node is dead
      changed_when: false
      when: ping_status.rc != 0
      set_fact:
          status: "dead"

    - local_action: copy content={{ ping.stdout }} /root/playbook2/output.txt
