---
##playbook to install packages

- hosts: install
  become: yes
  gather_facts: no
  tasks:
    apt:
      name: "{{packages}}"
      state: present
      vars:
        packages:
          - iotop
          - apache2
