---
- hosts: all
  become_user: ture
- name: to download
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb



  vars:
     download_url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  tasks:
      - name: install chrome
         apt: pkg=google-chrome-stable state=installed


---
- hosts: all
  become_user: ture
- name: to download
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  become: true
  register: apt_output
  when: ansible_os_family == 'Debian'
