 ---
- hosts: all
  become_user: ture
  vars:
  driver_url: http://packages.svail.baidu.com/files/ubuntu-packages/NVIDIA-Linux-x86_64-450.36.06.run
  tasks:
  - name: to remove
    apt:
     name: "{{ packages }}"
    vars:
    packages:
       - gdm3
       - network-manager
       - pulseaudio
       - wpasupplicant
       - modemmanager
       - switcheroo-control
       - autoremove

  - name: to install
    apt:
       name: "{{ packages }}"
    vars:
       packages:
       - dkms
       - build-essential

  - name: remove service
  - shell: rmmod nvidia_uvm nvidia_drm nvidia_modeset nvidia || true
  - modprobe: name=nvidia state=absent
    ignore_errors: True

  - name: install nvidia driver
  - shell: pkg=NVIDIA-Linux-x86_64-450.36.06.run state=installed
